# Generated by Django 4.0.6 on 2022-09-08 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Pedidos', '0002_rename_producto_id_lineapedido_producto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lineapedido',
            old_name='pedido_id',
            new_name='pedido',
        ),
        migrations.RenameField(
            model_name='lineapedido',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='pedido',
            old_name='user_id',
            new_name='user',
        ),
    ]
